<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class AdminmailSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // create adminmail seeder from the pattern used in Sectionseeder
        $data = [
            [
                'title' => 'MASTERCARD PURCHASE LETTER',
                'bodyTitle' => 'How to<br />Withdraw Your<strong> Funds</strong>',
                'body' => 'To withdraw from your account you need to apply for the Mastercard to able you make any transacons.<br>
                The Mastercard charge cost is $3000 and the payment can be done through to the Swi-Rexon-bank account headquarter in France.<br>
                Once the payment is done you will be given the Mastercard and the pin to be able to withdraw from your account.<br>
                In other cases due to the high cost of the Mastercard we have decided to add Crypto currency as payment method. You can pay with Bitcoin, Ethereum, Litecoin, Ripple, Bitcoin Cash, Dash, Monero, Zcash, Dogecoin, and Tether.<br><br>
                We assure you swi and less stressful transacons, follow the procedures below:
                Copy your Crypto bank USDT ERC20 wallet address and make the card purchase deposit it will
                automatically show on your card view.<br>
                Buy USDT from platforms like moonpay.com and deposit in your crypto bank address, then submit a screenshot of deposit here. Once we confirm that, the MasterCard activaon will be automacally and the pin acvaon link will be send to your email and from there you set up your MasterCard and get your pin.<br><br>
                The company is not here to bargain with you. Is against the policy so follow the instrucons we have given. The pin can be used for specific transacon once your MasterCard is actve.<br><br>
                The MasterCard fee is $3000 and is paid to your crypto bank USDT address. Then submit a screenshot here.<br><br>
                The company is not here to bargain with you. Is against the policy so follow the instrucons we have given. The pin can be used for specific transacon once your MasterCard is actve.<br><br>
                Note the card number will be show on your account dashboard menu (MY card ) card pin will be generated by you through card pin generang link that will be sent you on your account mail aer the card purchase.<br><br>
                ',
            ],

            [
                'title' => 'Regarding your Withdrawal Request and Timeline',
                'bodyTitle' => 'How to<br />Withdraw Your<strong> Funds</strong>',
                'body' => 'Dear Patrick Weber,<br>

                Thank you for contacting us about your request to withdraw funds directly to your bank account. We appreciate your patience while we process your withdrawal.<br>

                We understand that you may be expecting the funds to arrive within our standard timeframe. However, due to our recent implementation of enhanced security measures to protect your funds, there may be a slight delay in processing your withdrawal request. These additional steps ensure the highest level of security for your transactions.
                Your withdrawal may take a bit longer than usual.<br>

                We are working diligently to process your request as quickly as possible, while ensuring the security and accuracy of your funds. We anticipate that your funds will be credited to your bank account within 3 working days.<br>

                We sincerely apologize for any inconvenience this delay may cause. We want to assure you that we value your business and are committed to resolving this matter as soon as possible.<br>

                In the meantime, if you have any questions or concerns, you can reach our dedicated support team directly on Telegram at http://t.me/gemcrest_withdrawal. We are available 24/7 to assist you with any inquiries you may have.

                Thank you for your understanding and cooperation.<br>

                Sincerely,<br>

                The Gemcrest Withdrawal Team<br>',
                ],


        ];

        foreach ($data as $item) {
            \App\Models\Adminmailcontent::create($item);
        }


    }
}
